cd /home/s1785140/respeller

# Experiment 1/8: SweepGumbelTempFixedSchedules::gumbel_temp=2,0.5,0.999995
./sbatch.sh python train.py \
    --wandb-project-name respeller \
    --chkpt-save-dir /home/s1785140/respeller/exps/SweepGumbelTempFixedSchedules::gumbel_temp=2,0.5,0.999995 \
    --fastpitch-chkpt fastpitch/exps/halved_ljspeech_data_nospaces_noeos_pad_lowercase_nopunc/FastPitch_checkpoint_1000.pt \
    --input-type char \
    --symbol-set english_pad_lowercase_nopunc \
    --text-cleaners lowercase_no_punc \
    --use-mas \
    --cuda \
    --n-speakers 1 \
    --use-sepconv  \
    --respelling-len-modifier 0 \
    --nheads 2 \
    --num-layers 1 \
    --d-model 256 \
    --d-feedforward 512 \
    --dropout-inputs 0.0 \
    --dropout-layers 0.0 \
    --embedding-dim 384 \
    --freeze-embedding-table \
    --pretrained-embedding-table  \
    --gumbel-temp 2 0.5 0.999995 \
    --batch-size 64 \
    --seed 1337 \
    --val-num-to-gen 32 \
    --softdtw-temp 1.0 \
    --dist-func l1 \
    --learning-rate 0.1 \
    --epochs 2000 \
    --val-log-interval 20 \
    --epochs-per-checkpoint 20

# Experiment 2/8: SweepGumbelTempFixedSchedules::gumbel_temp=2,2,1.0
./sbatch.sh python train.py \
    --wandb-project-name respeller \
    --chkpt-save-dir /home/s1785140/respeller/exps/SweepGumbelTempFixedSchedules::gumbel_temp=2,2,1.0 \
    --fastpitch-chkpt fastpitch/exps/halved_ljspeech_data_nospaces_noeos_pad_lowercase_nopunc/FastPitch_checkpoint_1000.pt \
    --input-type char \
    --symbol-set english_pad_lowercase_nopunc \
    --text-cleaners lowercase_no_punc \
    --use-mas \
    --cuda \
    --n-speakers 1 \
    --use-sepconv  \
    --respelling-len-modifier 0 \
    --nheads 2 \
    --num-layers 1 \
    --d-model 256 \
    --d-feedforward 512 \
    --dropout-inputs 0.0 \
    --dropout-layers 0.0 \
    --embedding-dim 384 \
    --freeze-embedding-table \
    --pretrained-embedding-table  \
    --gumbel-temp 2 2 1.0 \
    --batch-size 64 \
    --seed 1337 \
    --val-num-to-gen 32 \
    --softdtw-temp 1.0 \
    --dist-func l1 \
    --learning-rate 0.1 \
    --epochs 2000 \
    --val-log-interval 20 \
    --epochs-per-checkpoint 20

# Experiment 3/8: SweepGumbelTempFixedSchedules::gumbel_temp=5,5,1.0
./sbatch.sh python train.py \
    --wandb-project-name respeller \
    --chkpt-save-dir /home/s1785140/respeller/exps/SweepGumbelTempFixedSchedules::gumbel_temp=5,5,1.0 \
    --fastpitch-chkpt fastpitch/exps/halved_ljspeech_data_nospaces_noeos_pad_lowercase_nopunc/FastPitch_checkpoint_1000.pt \
    --input-type char \
    --symbol-set english_pad_lowercase_nopunc \
    --text-cleaners lowercase_no_punc \
    --use-mas \
    --cuda \
    --n-speakers 1 \
    --use-sepconv  \
    --respelling-len-modifier 0 \
    --nheads 2 \
    --num-layers 1 \
    --d-model 256 \
    --d-feedforward 512 \
    --dropout-inputs 0.0 \
    --dropout-layers 0.0 \
    --embedding-dim 384 \
    --freeze-embedding-table \
    --pretrained-embedding-table  \
    --gumbel-temp 5 5 1.0 \
    --batch-size 64 \
    --seed 1337 \
    --val-num-to-gen 32 \
    --softdtw-temp 1.0 \
    --dist-func l1 \
    --learning-rate 0.1 \
    --epochs 2000 \
    --val-log-interval 20 \
    --epochs-per-checkpoint 20

# Experiment 4/8: SweepGumbelTempFixedSchedules::gumbel_temp=1,1,1.0
./sbatch.sh python train.py \
    --wandb-project-name respeller \
    --chkpt-save-dir /home/s1785140/respeller/exps/SweepGumbelTempFixedSchedules::gumbel_temp=1,1,1.0 \
    --fastpitch-chkpt fastpitch/exps/halved_ljspeech_data_nospaces_noeos_pad_lowercase_nopunc/FastPitch_checkpoint_1000.pt \
    --input-type char \
    --symbol-set english_pad_lowercase_nopunc \
    --text-cleaners lowercase_no_punc \
    --use-mas \
    --cuda \
    --n-speakers 1 \
    --use-sepconv  \
    --respelling-len-modifier 0 \
    --nheads 2 \
    --num-layers 1 \
    --d-model 256 \
    --d-feedforward 512 \
    --dropout-inputs 0.0 \
    --dropout-layers 0.0 \
    --embedding-dim 384 \
    --freeze-embedding-table \
    --pretrained-embedding-table  \
    --gumbel-temp 1 1 1.0 \
    --batch-size 64 \
    --seed 1337 \
    --val-num-to-gen 32 \
    --softdtw-temp 1.0 \
    --dist-func l1 \
    --learning-rate 0.1 \
    --epochs 2000 \
    --val-log-interval 20 \
    --epochs-per-checkpoint 20

# Experiment 5/8: SweepGumbelTempFixedSchedules::gumbel_temp=10,10,1.0
./sbatch.sh python train.py \
    --wandb-project-name respeller \
    --chkpt-save-dir /home/s1785140/respeller/exps/SweepGumbelTempFixedSchedules::gumbel_temp=10,10,1.0 \
    --fastpitch-chkpt fastpitch/exps/halved_ljspeech_data_nospaces_noeos_pad_lowercase_nopunc/FastPitch_checkpoint_1000.pt \
    --input-type char \
    --symbol-set english_pad_lowercase_nopunc \
    --text-cleaners lowercase_no_punc \
    --use-mas \
    --cuda \
    --n-speakers 1 \
    --use-sepconv  \
    --respelling-len-modifier 0 \
    --nheads 2 \
    --num-layers 1 \
    --d-model 256 \
    --d-feedforward 512 \
    --dropout-inputs 0.0 \
    --dropout-layers 0.0 \
    --embedding-dim 384 \
    --freeze-embedding-table \
    --pretrained-embedding-table  \
    --gumbel-temp 10 10 1.0 \
    --batch-size 64 \
    --seed 1337 \
    --val-num-to-gen 32 \
    --softdtw-temp 1.0 \
    --dist-func l1 \
    --learning-rate 0.1 \
    --epochs 2000 \
    --val-log-interval 20 \
    --epochs-per-checkpoint 20

# Experiment 6/8: SweepGumbelTempFixedSchedules::gumbel_temp=0.5,0.5,1.0
./sbatch.sh python train.py \
    --wandb-project-name respeller \
    --chkpt-save-dir /home/s1785140/respeller/exps/SweepGumbelTempFixedSchedules::gumbel_temp=0.5,0.5,1.0 \
    --fastpitch-chkpt fastpitch/exps/halved_ljspeech_data_nospaces_noeos_pad_lowercase_nopunc/FastPitch_checkpoint_1000.pt \
    --input-type char \
    --symbol-set english_pad_lowercase_nopunc \
    --text-cleaners lowercase_no_punc \
    --use-mas \
    --cuda \
    --n-speakers 1 \
    --use-sepconv  \
    --respelling-len-modifier 0 \
    --nheads 2 \
    --num-layers 1 \
    --d-model 256 \
    --d-feedforward 512 \
    --dropout-inputs 0.0 \
    --dropout-layers 0.0 \
    --embedding-dim 384 \
    --freeze-embedding-table \
    --pretrained-embedding-table  \
    --gumbel-temp 0.5 0.5 1.0 \
    --batch-size 64 \
    --seed 1337 \
    --val-num-to-gen 32 \
    --softdtw-temp 1.0 \
    --dist-func l1 \
    --learning-rate 0.1 \
    --epochs 2000 \
    --val-log-interval 20 \
    --epochs-per-checkpoint 20

# Experiment 7/8: SweepGumbelTempFixedSchedules::gumbel_temp=0.1,0.1,1.0
./sbatch.sh python train.py \
    --wandb-project-name respeller \
    --chkpt-save-dir /home/s1785140/respeller/exps/SweepGumbelTempFixedSchedules::gumbel_temp=0.1,0.1,1.0 \
    --fastpitch-chkpt fastpitch/exps/halved_ljspeech_data_nospaces_noeos_pad_lowercase_nopunc/FastPitch_checkpoint_1000.pt \
    --input-type char \
    --symbol-set english_pad_lowercase_nopunc \
    --text-cleaners lowercase_no_punc \
    --use-mas \
    --cuda \
    --n-speakers 1 \
    --use-sepconv  \
    --respelling-len-modifier 0 \
    --nheads 2 \
    --num-layers 1 \
    --d-model 256 \
    --d-feedforward 512 \
    --dropout-inputs 0.0 \
    --dropout-layers 0.0 \
    --embedding-dim 384 \
    --freeze-embedding-table \
    --pretrained-embedding-table  \
    --gumbel-temp 0.1 0.1 1.0 \
    --batch-size 64 \
    --seed 1337 \
    --val-num-to-gen 32 \
    --softdtw-temp 1.0 \
    --dist-func l1 \
    --learning-rate 0.1 \
    --epochs 2000 \
    --val-log-interval 20 \
    --epochs-per-checkpoint 20

# Experiment 8/8: SweepGumbelTempFixedSchedules::gumbel_temp=0.01,0.01,1.0
./sbatch.sh python train.py \
    --wandb-project-name respeller \
    --chkpt-save-dir /home/s1785140/respeller/exps/SweepGumbelTempFixedSchedules::gumbel_temp=0.01,0.01,1.0 \
    --fastpitch-chkpt fastpitch/exps/halved_ljspeech_data_nospaces_noeos_pad_lowercase_nopunc/FastPitch_checkpoint_1000.pt \
    --input-type char \
    --symbol-set english_pad_lowercase_nopunc \
    --text-cleaners lowercase_no_punc \
    --use-mas \
    --cuda \
    --n-speakers 1 \
    --use-sepconv  \
    --respelling-len-modifier 0 \
    --nheads 2 \
    --num-layers 1 \
    --d-model 256 \
    --d-feedforward 512 \
    --dropout-inputs 0.0 \
    --dropout-layers 0.0 \
    --embedding-dim 384 \
    --freeze-embedding-table \
    --pretrained-embedding-table  \
    --gumbel-temp 0.01 0.01 1.0 \
    --batch-size 64 \
    --seed 1337 \
    --val-num-to-gen 32 \
    --softdtw-temp 1.0 \
    --dist-func l1 \
    --learning-rate 0.1 \
    --epochs 2000 \
    --val-log-interval 20 \
    --epochs-per-checkpoint 20

